CREATE TABLE IF NOT EXISTS `tbl_pos_developer_account` (
  `singleton_id` TINYINT UNSIGNED NOT NULL,
  `subject_id` INT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `display_name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `is_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `credential_version` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`singleton_id`),
  UNIQUE KEY `uq_tbl_pos_developer_account_subject` (`subject_id`),
  UNIQUE KEY `uq_tbl_pos_developer_account_username` (`username`),
  CONSTRAINT `chk_tbl_pos_developer_account_singleton`
    CHECK (`singleton_id` = 1),
  CONSTRAINT `chk_tbl_pos_developer_account_subject`
    CHECK (`subject_id` BETWEEN 1 AND 2147483647)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- The Developer password hash is deployment-specific and is intentionally not
-- committed here. Insert the singleton row with singleton_id = 1 during
-- deployment, using a PASSWORD_BCRYPT hash generated by PHP.
